package com.mds.decisionsupport;

rule "insert_process_variable_into_wm"
dialect "mvel"
salience 10
no-loop true
ruleflow-group "triage"
when
$processInstance : org.kie.api.runtime.process.WorkflowProcessInstance( )
$record : com.mds.decisionsupport.MedicalRecord( this != null) from (com.mds.decisionsupport.MedicalRecord) $processInstance.getVariable("mr") 

then
System.out.println("inserting process variable into wm");
insert($record);
end
