package com.mds.decisionsupport;


rule "set process variable result"
dialect "mvel"
ruleflow-group "triage"
when
$processInstance : org.kie.api.runtime.process.WorkflowProcessInstance( $results : this.getVariable("engineResults") != null )
$result : com.mds.decisionsupport.InferenceEngineResult( )
then
System.out.println("Test update process instance result ");

com.mds.decisionsupport.Results resultList = ((com.mds.decisionsupport.Results)$results);

resultList.addInferenceEngineResult($result );
$processInstance.setVariable("engineResults",resultList );
end
