package com.mds.decisionsupport;

/**
 * This class was automatically generated by the data modeler tool.
 */
@org.kie.api.definition.type.Label(value = "Bioportal Context")
public class BioportalContext  implements java.io.Serializable {

static final long serialVersionUID = 1L;
    
    @org.kie.api.definition.type.Key
    @org.kie.api.definition.type.Label(value = "Definition")
    @org.kie.api.definition.type.Position(value = 3)
    private java.lang.String definition;
    
    @org.kie.api.definition.type.Key
    @org.kie.api.definition.type.Label(value = "Obsolete")
    @org.kie.api.definition.type.Position(value = 4)
    private java.lang.String obsolete;
    
    @org.kie.api.definition.type.Key
    @org.kie.api.definition.type.Label(value = "Pref Label")
    @org.kie.api.definition.type.Position(value = 1)
    private java.lang.String prefLabel;
    
    @org.kie.api.definition.type.Key
    @org.kie.api.definition.type.Label(value = "Synonym")
    @org.kie.api.definition.type.Position(value = 2)
    private java.lang.String synonym;
    
    @org.kie.api.definition.type.Key
    @org.kie.api.definition.type.Label(value = "@vocab")
    @org.kie.api.definition.type.Position(value = 0)
    private java.lang.String vocab;

    public BioportalContext() {
    }

    public BioportalContext(java.lang.String vocab, java.lang.String prefLabel, java.lang.String synonym, java.lang.String definition, java.lang.String obsolete) {
        this.vocab = vocab;
        this.prefLabel = prefLabel;
        this.synonym = synonym;
        this.definition = definition;
        this.obsolete = obsolete;
    }


    
    public java.lang.String getDefinition() {
        return this.definition;
    }

    public void setDefinition(  java.lang.String definition ) {
        this.definition = definition;
    }
    
    public java.lang.String getObsolete() {
        return this.obsolete;
    }

    public void setObsolete(  java.lang.String obsolete ) {
        this.obsolete = obsolete;
    }
    
    public java.lang.String getPrefLabel() {
        return this.prefLabel;
    }

    public void setPrefLabel(  java.lang.String prefLabel ) {
        this.prefLabel = prefLabel;
    }
    
    public java.lang.String getSynonym() {
        return this.synonym;
    }

    public void setSynonym(  java.lang.String synonym ) {
        this.synonym = synonym;
    }
    
    public java.lang.String getVocab() {
        return this.vocab;
    }

    public void setVocab(  java.lang.String vocab ) {
        this.vocab = vocab;
    }

    @Override
    public boolean equals(Object o) {
        if (this == o) return true;
        if (o == null || getClass() != o.getClass()) return false;
        com.mds.decisionsupport.BioportalContext that = (com.mds.decisionsupport.BioportalContext)o;
        if (definition != null ? !definition.equals(that.definition) : that.definition != null) return false;
        if (obsolete != null ? !obsolete.equals(that.obsolete) : that.obsolete != null) return false;
        if (prefLabel != null ? !prefLabel.equals(that.prefLabel) : that.prefLabel != null) return false;
        if (synonym != null ? !synonym.equals(that.synonym) : that.synonym != null) return false;
        if (vocab != null ? !vocab.equals(that.vocab) : that.vocab != null) return false;
        return true;
    }

    @Override
    public int hashCode() {
        int result = 17;
        result = 13 * result + (definition != null ? definition.hashCode() : 0);
        result = 13 * result + (obsolete != null ? obsolete.hashCode() : 0);
        result = 13 * result + (prefLabel != null ? prefLabel.hashCode() : 0);
        result = 13 * result + (synonym != null ? synonym.hashCode() : 0);
        result = 13 * result + (vocab != null ? vocab.hashCode() : 0);
        return result;
    }
}