package com.mds.decisionsupport;

/**
 * This class was automatically generated by the data modeler tool.
 */
@org.kie.api.definition.type.Label(value = "Snomed Clinical Terms")
public class SnomedCT  implements java.io.Serializable {

static final long serialVersionUID = 1L;
    
    @org.kie.api.definition.type.Key
    @org.kie.api.definition.type.Label(value = "Definitions")
    @org.kie.api.definition.type.Position(value = 3)
    private java.lang.String definitions;
    
    @org.kie.api.definition.type.Key
    @org.kie.api.definition.type.Label(value = "Preferred description")
    @org.kie.api.definition.type.Position(value = 1)
    private java.lang.String descriptionPreferred;
    
    @org.kie.api.definition.type.Key
    @org.kie.api.definition.type.Label(value = "Synonyms")
    @org.kie.api.definition.type.Position(value = 2)
    private java.lang.String synonyms;
    
    @org.kie.api.definition.type.Key
    @org.kie.api.definition.type.Label(value = "Uri")
    @org.kie.api.definition.type.Position(value = 0)
    private java.lang.String uri;

    public SnomedCT() {
    }

    public SnomedCT(java.lang.String uri, java.lang.String descriptionPreferred, java.lang.String synonyms, java.lang.String definitions) {
        this.uri = uri;
        this.descriptionPreferred = descriptionPreferred;
        this.synonyms = synonyms;
        this.definitions = definitions;
    }


    
    public java.lang.String getDefinitions() {
        return this.definitions;
    }

    public void setDefinitions(  java.lang.String definitions ) {
        this.definitions = definitions;
    }
    
    public java.lang.String getDescriptionPreferred() {
        return this.descriptionPreferred;
    }

    public void setDescriptionPreferred(  java.lang.String descriptionPreferred ) {
        this.descriptionPreferred = descriptionPreferred;
    }
    
    public java.lang.String getSynonyms() {
        return this.synonyms;
    }

    public void setSynonyms(  java.lang.String synonyms ) {
        this.synonyms = synonyms;
    }
    
    public java.lang.String getUri() {
        return this.uri;
    }

    public void setUri(  java.lang.String uri ) {
        this.uri = uri;
    }

    @Override
    public boolean equals(Object o) {
        if (this == o) return true;
        if (o == null || getClass() != o.getClass()) return false;
        com.mds.decisionsupport.SnomedCT that = (com.mds.decisionsupport.SnomedCT)o;
        if (definitions != null ? !definitions.equals(that.definitions) : that.definitions != null) return false;
        if (descriptionPreferred != null ? !descriptionPreferred.equals(that.descriptionPreferred) : that.descriptionPreferred != null) return false;
        if (synonyms != null ? !synonyms.equals(that.synonyms) : that.synonyms != null) return false;
        if (uri != null ? !uri.equals(that.uri) : that.uri != null) return false;
        return true;
    }

    @Override
    public int hashCode() {
        int result = 17;
        result = 13 * result + (definitions != null ? definitions.hashCode() : 0);
        result = 13 * result + (descriptionPreferred != null ? descriptionPreferred.hashCode() : 0);
        result = 13 * result + (synonyms != null ? synonyms.hashCode() : 0);
        result = 13 * result + (uri != null ? uri.hashCode() : 0);
        return result;
    }
}